# How links connect together
kinematics:
  joint0:
    x: 0.0
    y: 0.0
    z: 0.257
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  joint1:
    x: 0.0
    y: -0.0845
    z: 0.084
    roll: 1.570796327
    pitch: 0.0
    yaw: 0.0
  joint2:
    x: 0.0
    y: 0.450
    z: -0.0005
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  joint3:
    x: 0.0
    y: 0.055
    z: -0.0845
    roll: -1.570796327
    pitch: 0.0
    yaw: 0.0
  joint4:
    x: 0.0
    y: 0.05
    z: 0.395
    roll: 1.570796327
    pitch: 0.0
    yaw: 0.0
  joint5:
    x: 0.0
    y: 0.05
    z: 0.0495
    roll: -1.570796327
    pitch: 0.0
    yaw: 0.0
  tcp:
    x: 0.0
    y: 0.0
    z: 0.0605
    roll: 0.0
    pitch: 0.0
    yaw: 0.0