mesh_files:
  link0:
    visual:
      mesh:
        package: indy_description
        path: meshes/opti5/visual/Opti5_0.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/opti5/collision/Opti5_0.stl
  link1:
    visual:
      mesh:
        package: indy_description
        path: meshes/opti5/visual/Opti5_1.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/opti5/collision/Opti5_1.stl
  link2:
    visual:
      mesh:
        package: indy_description
        path: meshes/opti5/visual/Opti5_2.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/opti5/collision/Opti5_2.stl
  link3:
    visual:
      mesh:
        package: indy_description
        path: meshes/opti5/visual/Opti5_3.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/opti5/collision/Opti5_3.stl
  link4:
    visual:
      mesh:
        package: indy_description
        path: meshes/opti5/visual/Opti5_4.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/opti5/collision/Opti5_4.stl
  link5:
    visual:
      mesh:
        package: indy_description
        path: meshes/opti5/visual/Opti5_5.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/opti5/collision/Opti5_5.stl
  link6:
    visual:
      mesh:
        package: indy_description
        path: meshes/opti5/visual/Opti5_6.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/opti5/collision/Opti5_6.stl
