# How links connect together
kinematics:
  joint0:
    x: 0.0
    y: 0.0
    z: 0.19825
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  joint1:
    x: 0.025
    y: 0.0
    z: 0.202
    roll: -1.570796327
    pitch: 0.0
    yaw: 0.0
  joint2:
    x: 0.0
    y: -0.463
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 1.570796327
  joint3:
    x: -0.035
    y: -0.182
    z: 0.0
    roll: 1.570796327
    pitch: 1.570796327
    yaw: 0.0
  joint4:
    x: 0.0
    y: 0.0
    z: 0.25
    roll: 1.570796327
    pitch: 0.0
    yaw: -1.570796327
  joint5:
    x: 0.0
    y: 0.089
    z: 0.0
    roll: 1.570796327
    pitch: 0.0
    yaw: 3.14159265
  tcp:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0