inertia_parameters:
  link0_mass: 0.858186768
  link1_mass: 2.520440484
  link2_mass: 3.1785267
  link3_mass: 1.601379441
  link4_mass: 1.882223023
  link5_mass: 1.507185922
  link6_mass: 0.634034296

  link0:
    ixx: 0.001565927
    iyy: 0.001520073
    izz: 0.001972781
    iyz: -0.000044915
    ixz: -0.000000965
    ixy: -0.000000108

  link1:
    ixx: 0.021369338
    iyy: 0.020930725
    izz: 0.004182258
    iyz: -0.001763079
    ixz: -0.000003834
    ixy: 0.000000113

  link2:
    ixx: 0.061307300
    iyy: 0.061429858
    izz: 0.008932949
    iyz: -0.000301492
    ixz: 0.008654534
    ixy: 0.000497436

  link3:
    ixx: 0.006489986
    iyy: 0.007023542
    izz: 0.003296162
    iyz: -0.000818226
    ixz: 0.001710122
    ixy: -0.000525078

  link4:
    ixx: 0.013319852
    iyy: 0.012519892
    izz: 0.002788281
    iyz: -0.001438940
    ixz: 0.000000867
    ixy: -0.000001850

  link5:
    ixx: 0.005032625
    iyy: 0.002614418
    izz: 0.003944803
    iyz: -0.000331648
    ixz: -0.000001293
    ixy: -0.000006075

  link6:
    ixx: 0.000997016
    iyy: 0.001002530
    izz: 0.000447948
    iyz: 0.000001581
    ixz: 0.000000897
    ixy: -0.000001376
    
  center_of_mass:
    link0:
      x: -0.033213
      y: -0.001385
      z: 0.101897
    link1:
      x: 0.001336
      y: 0.017855
      z: 0.261572
    link2:
      x: -0.012687
      y: 0.008506
      z: 0.411406
    link3:
      x: -0.007513
      y: 0.016906
      z: 0.583953
    link4:
      x: 0.150496
      y: -0.000380
      z: 0.609627
    link5:
      x: 0.319227
      y: 0.001458
      z: 0.610932
    link6:
      x: 0.0
      y: 0.0
      z: 0.0
