mesh_files:
  link0:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri4s/visual/Nuri4s_0.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri4s/collision/Nuri4s_0.stl
  link1:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri4s/visual/Nuri4s_1.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri4s/collision/Nuri4s_1.stl
  link2:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri4s/visual/Nuri4s_2.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri4s/collision/Nuri4s_2.stl
  link3:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri4s/visual/Nuri4s_3.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri4s/collision/Nuri4s_3.stl
  link4:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri4s/visual/Nuri4s_4.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri4s/collision/Nuri4s_4.stl
  link5:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri4s/visual/Nuri4s_5.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri4s/collision/Nuri4s_5.stl
  link6:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri4s/visual/Nuri4s_6.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri4s/collision/Nuri4s_6.stl
