# How links connect together
kinematics:
  joint0:
    x: 0.0
    y: 0.0
    z: 0.09
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  joint1:
    x: 0.0
    y: -0.040
    z: 0.223
    roll: 1.570796327
    pitch: 0.0
    yaw: 0.0
  joint2:
    x: 0.05023
    y: 0.2900135
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  joint3:
    x: -0.050
    y: 0.085
    z: -0.040
    roll: -1.570796327
    pitch: 0.0
    yaw: 0.0
  joint4:
    x: 0.0
    y: 0.070
    z: 0.2050424
    roll: 1.570796327
    pitch: 0.0
    yaw: 0.0
  joint5:
    x: 0.0
    y: 0.075
    z: -0.066
    roll: -1.570796327
    pitch: 0.0
    yaw: 0.0
  tcp:
    x: 0.0
    y: 0.0
    z: 0.0285
    roll: 0.0
    pitch: 0.0
    yaw: 0.0