mesh_files:
  link0:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri3s/visual/Nuri3s_0.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri3s/collision/Nuri3s_0.stl
  link1:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri3s/visual/Nuri3s_1.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri3s/collision/Nuri3s_1.stl
  link2:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri3s/visual/Nuri3s_2.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri3s/collision/Nuri3s_2.stl
  link3:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri3s/visual/Nuri3s_3.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri3s/collision/Nuri3s_3.stl
  link4:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri3s/visual/Nuri3s_4.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri3s/collision/Nuri3s_4.stl
  link5:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri3s/visual/Nuri3s_5.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri3s/collision/Nuri3s_5.stl
  link6:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri3s/visual/Nuri3s_6.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri3s/collision/Nuri3s_6.stl
