joint_limits:
  joint0:
    has_effort_limits: true
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: false
    max_effort: 431.97
    max_velocity: !degrees 450.0
    max_position: !degrees 170.0
    min_position: !degrees -170.0
  joint1:
    has_effort_limits: true
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: false
    max_effort: 431.97
    max_velocity: !degrees 450.0
    max_position: !degrees  120.0
    min_position: !degrees -110.0
  joint2:
    has_effort_limits: true
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: false
    max_effort: 197.23
    max_velocity: !degrees 525.0
    max_position: !degrees 62.0 #152.0
    min_position: !degrees -198.0 #-108.0
  joint3:
    has_effort_limits: true
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: false
    max_effort: 79.79
    max_velocity: !degrees 600.0
    max_position: !degrees 200.0
    min_position: !degrees -200.0
  joint4:
    has_effort_limits: true
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: false
    max_effort: 79.79
    max_velocity: !degrees 600.0
    max_position: !degrees 118.0
    min_position: !degrees -118.0
  joint5:
    has_effort_limits: true
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: false
    max_effort: 79.79
    max_velocity: !degrees 800.0
    max_position: !degrees  350.0
    min_position: !degrees -350.0
    