joint_state_controller:
    type:   "joint_state_controller/JointStateController"
    publish_rate:   50

indy7_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint0
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5

  gains:
    joint0:
      {p: 100.0, i: 0.01, d:  10.0, i_clamp: 0}
    joint1:
      {p: 100.0, i: 0.01, d:  10.0, i_clamp: 0}
    joint2:
      {p: 100.0, i: 0.01, d:  10.0, i_clamp: 0}
    joint3:
      {p: 100.0, i: 0.01, d:  10.0, i_clamp: 0}
    joint4:
      {p: 100.0, i: 0.01, d:  10.0, i_clamp: 0}
    joint5:
      {p: 100.0, i: 0.01, d:  10.0, i_clamp: 0}

gazebo_ros_control: 
  pid_gains:
    joint0:
      p: 100.0
      i: 0.01 
      d: 10.0
    joint1:
      p: 100.0
      i: 0.01 
      d: 10.0
    joint2:
      p: 100.0
      i: 0.01 
      d: 10.0
    joint3:
      p: 100.0
      i: 0.01 
      d: 10.0
    joint4:
      p: 100.0
      i: 0.01 
      d: 10.0            
    joint5:
      p: 100.0
      i: 0.01 
      d: 10.0      